version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: base
    command: >
      postgres
        -c max_locks_per_transaction=256
        -c shared_buffers=2GB
        -c work_mem=128MB
        -c maintenance_work_mem=256MB
        -c effective_cache_size=6GB
        -c max_connections=200
        -c max_parallel_workers_per_gather=4
        -c max_parallel_workers=8
        -c max_worker_processes=8
        -c random_page_cost=1.1
        -c checkpoint_timeout=15min
        -c max_wal_size=2GB
        -c min_wal_size=1GB
        -c wal_buffers=16MB
        -c enable_partition_pruning=on
        -c autovacuum=on
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # Add resource limits to ensure PostgreSQL can use allocated memory
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  # Optional: Add connection pooling with PgBouncer
  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=base
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=50
      - RESERVE_POOL_SIZE=50
      - RESERVE_POOL_TIMEOUT=5
    ports:
      - "6432:6432"
    depends_on:
      - db